apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: cs3219
spec:
  selector:
    app: catalog-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
